---
- name: install dependencies for rbenv
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  yum: name={{ item }} state=latest
  with_items:
    - git
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: install dependencies for rbenv
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  apt: name={{ item }} state=latest
  with_items:
    - git
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: install rbenv
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.version }}
  with_items:
    - { repo: 'https://github.com/sstephenson/rbenv.git', dest: '~/.rbenv', version: "{{ rbenv.version }}" }
  tags: rbenv

- name: add ~.rbenv/bin to PATH
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: add ~.rbenv/bin to PATH
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: eval rbenv init in ~/.bash_profile
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.bash_profile"
    line='eval "$(rbenv init -)"'
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: eval rbenv init in ~/.profile
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: install dependencies for ruby-build
  yum: name={{ item }} state=latest
  with_items:
    - openssl-devel
    - readline-devel
    - zlib-devel
    - gcc-c++
  when: ansible_os_family == "RedHat"
  tags: rbenv

- name: install dependencies for ruby-build
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
  when: ansible_os_family == "Debian"
  tags: rbenv

- name: install ruby-build
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  git: repo={{ item.repo }} dest={{ item.dest }} version={{ item.version }}
  with_items:
    - { repo: 'https://github.com/sstephenson/ruby-build.git', dest: '~/.rbenv/plugins/ruby-build', version: "{{ rbenv.ruby_build_version }}" }
  tags: rbenv

- name: check if version is installed ruby
  shell: "sudo -iu {{ rbenv.user }} rbenv versions | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes
  tags: rbenv

- name: install ruby
  command: "sudo -iu {{ rbenv.user }} rbenv install {{ rbenv.ruby_version }}"
  when: rbenv_check_install|failed
  tags: rbenv

- name: check default ruby version
  shell: "sudo -iu {{ rbenv.user }} rbenv version | grep {{ rbenv.ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes
  tags: rbenv

- name: set default ruby version
  command: "sudo -iu {{ rbenv.user }} rbenv global {{ rbenv.ruby_version }}"
  when: rbenv_check_default|failed
  tags: rbenv
